---
- name: Ensure Apache installed
  yum: name=httpd state=present

- name: Start Apache
  service: name=httpd state=started enabled=yes

- name: Copy site files
  template: src=index.j2 dest=/var/www/html/index.html

- name: IP Tables Stop
  service: name=iptables state=stopped
